import { withPayload } from '@payloadcms/next/withPayload'

import redirects from './redirects.js'

const NEXT_PUBLIC_SERVER_URL = process.env.VERCEL_PROJECT_PRODUCTION_URL
  ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
  : undefined || process.env.__NEXT_PRIVATE_ORIGIN || 'http://localhost:3000'

/** @type {import('next').NextConfig} */
const nextConfig = {
  // `next build`'s route-type validation (Next 15.5) rejects Payload 3.48's
  // AUTO-GENERATED route handlers (src/app/(payload)/api/graphql, api/[...slug],
  // graphql-playground) — they export @payloadcms/next handlers whose types
  // predate Next 15.5's stricter `RouteHandlerConfig`. Those files are marked
  // "DO NOT MODIFY" (regenerated by Payload), so this is a framework version
  // incompatibility, NOT an app-code bug.
  //
  // The app's own code IS type-clean: `pnpm exec tsc --noEmit` returns 0
  // errors — run THAT as the type-safety gate. Drop this flag once
  // @payloadcms/next is upgraded to a Next-15.5-compatible release.
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    // AVIF first (≈30–50% smaller than WebP), then WebP fallback. The
    // optimizer negotiates format via the Accept header — these do NOT
    // change the rendered <img> srcSet, so they're hydration-safe.
    formats: ['image/avif', 'image/webp'],
    // Next 15.5+: declare the quality values used so server + client
    // agree (Media defaults to 80; some non-Media images use Next's
    // default 75). Without this, a custom quality can desync SSR vs
    // client and trigger a hydration mismatch.
    qualities: [75, 80],
    remotePatterns: [
      ...[NEXT_PUBLIC_SERVER_URL /* 'https://example.com' */].map((item) => {
        const url = new URL(item)

        return {
          hostname: url.hostname,
          protocol: url.protocol.replace(':', ''),
        }
      }),
      // Allow Next/Image to optimise images requested from Cloudflare
      // Quick Tunnel + ngrok hostnames when the site is being shared
      // publicly via tunnel. Without this, `<Media fill>` throws
      // "hostname is not configured under images" because the
      // generated `/api/media/file/...` URL uses the tunnel host
      // rather than localhost.
      { hostname: '*.trycloudflare.com', protocol: 'https' },
      { hostname: '*.ngrok-free.app', protocol: 'https' },
      { hostname: '*.ngrok.app', protocol: 'https' },
      // Production media — Vercel Blob serves uploads from this
      // subdomain pattern (e.g. `<hash>.public.blob.vercel-storage.com`).
      // Without the whitelist, next/image refuses to optimise images
      // served from Blob after the storage adapter is active.
      { hostname: '*.public.blob.vercel-storage.com', protocol: 'https' },
    ],
  },
  webpack: (webpackConfig) => {
    webpackConfig.resolve.extensionAlias = {
      '.cjs': ['.cts', '.cjs'],
      '.js': ['.ts', '.tsx', '.js', '.jsx'],
      '.mjs': ['.mts', '.mjs'],
    }

    return webpackConfig
  },
  reactStrictMode: true,
  // Allow cross-origin requests from Cloudflare Quick Tunnel hosts
  // (e.g. `*.trycloudflare.com`) and ngrok-style tunnels during dev.
  // Without this, Next.js 15+ blocks dev-time HMR + RSC requests from
  // non-localhost origins as a CSRF guard.
  allowedDevOrigins: ['*.trycloudflare.com', '*.ngrok-free.app', '*.ngrok.app'],
  redirects,
}

export default withPayload(nextConfig, { devBundleServerPackages: false })
