import type { MetadataRoute } from 'next'

import { getServerSideURL } from '@/utilities/getURL'

/**
 * Dynamic robots.txt.
 *
 * Replaces the old `next-sitemap` static file, which baked in a localhost
 * URL (generated by a local build, then uploaded as a static /public file)
 * — so Google was pointed at `http://localhost:3000/sitemap.xml` and could
 * never fetch the sitemap.
 *
 * `getServerSideURL()` resolves to https://momhindia.org on Vercel (via
 * VERCEL_PROJECT_PRODUCTION_URL), so the Sitemap directive + host are always
 * the real production domain. Generated server-side per request — no static
 * file to drift.
 */
export default function robots(): MetadataRoute.Robots {
  const url = getServerSideURL()

  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: ['/admin/', '/api/'],
    },
    sitemap: `${url}/sitemap.xml`,
    host: url,
  }
}
