/*
 * Regenerated by `payload migrate:create`. NOT the source of truth for what
 * runs: Payload's readMigrationFiles() scans this directory and explicitly
 * skips index.ts, so every migration FILE here is applied in filename order
 * regardless of what this array says.
 *
 * (A previous comment here claimed 20250728_070911 was "intentionally not
 * registered" and therefore inert. It is not inert — it runs. Verified by
 * applying migrations to a scratch database: both it and initial_v2 apply.)
 */
import * as migration_20250728_070911 from './20250728_070911';
import * as migration_20260527_050504_initial_v2 from './20260527_050504_initial_v2';
import * as migration_20260818_104430_founders_vision_blocks from './20260818_104430_founders_vision_blocks';

export const migrations = [
  {
    up: migration_20250728_070911.up,
    down: migration_20250728_070911.down,
    name: '20250728_070911',
  },
  {
    up: migration_20260527_050504_initial_v2.up,
    down: migration_20260527_050504_initial_v2.down,
    name: '20260527_050504_initial_v2',
  },
  {
    up: migration_20260818_104430_founders_vision_blocks.up,
    down: migration_20260818_104430_founders_vision_blocks.down,
    name: '20260818_104430_founders_vision_blocks'
  },
];
